### ISSUE TITLE
symfony6 

### ISSUE THREAD

**Issue by MarcFarres** [jolicode/elastically#102]
Hi, I wanted to ask if you plan to give support to symfony 6  that requires php8.
when i tried to install your package composer throws that error:

 Problem 1
    - jolicode/elastically[v1.5.0, ..., v1.5.1] require ruflin/elastica ^7.0 -> satisfiable by ruflin/elastica[7.0.0, ..., 7.1.3].
    - ruflin/elastica[7.1.2, ..., 7.1.3] require elasticsearch/elasticsearch ^7.1.1 -> satisfiable by elasticsearch/elasticsearch[v7.1.1, ..., v7.16.0].
    - elasticsearch/elasticsearch[v7.1.1, ..., v7.10.0] require php ^7.1 -> your php version (8.0.15) does not satisfy that requirement.

thank you.

**Comment by jdreesen** [comment]
Seems like something else in your `composer.json` is preventing the installation of `elasticsearch/elasticsearch` `>=v7.11`, which is needed for PHP 8.

Did you try to run `composer require jolicode/elastically` with the `--update-with-all-dependencies` flag?
You could also try to run `composer why elasticsearch/elasticsearch` to find out what else is requiring that dependency.

**Comment by MarcFarres** [comment]
composer require jolicode/elastically --update-with-all-dependencies    works fine for the moment
thanks you a lot for your fast response.
