### ISSUE TITLE
Elasticaly cluster configuration

### ISSUE THREAD

**Issue by issam-chouchane** [jolicode/elastically#104]
In .Net libraries we can set a cluster config in the Elastic client part by specifying the master and slaves.
Can we do the same with Elasticaly, if yes could you provide an exemple of the de Yaml please ?

Thnx.

**Comment by lyrixx** [comment]
Do you have a link to the .Net lib?

**Comment by issam-chouchane** [comment]
You can check the library proposed by Elasticsearch : 

- https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/connecting.html

![image](https://user-images.githubusercontent.com/911088/163989760-2cc908ca-9baa-4a56-ba1f-43ff94e11b4f.png)

**Comment by damienalexandre** [comment]
Elastically rely on Elastica, you can have a look here:

https://github.com/ruflin/Elastica/blob/a97ede932024d26bdca8bb05eb3abe3c7942ddbc/src/Client.php#L615-L664

So something like this should work:

```php
// Factory object with Elastica options + new Elastically options in the same array
$factory = new Factory([
    // Where to find the mappings
    Factory::CONFIG_MAPPINGS_DIRECTORY => __DIR__.'/mappings',
    // What object to find in each index
    Factory::CONFIG_INDEX_CLASS_MAPPING => [
        'beers' => Beer::class,
    ],
    'connections' => [
            ['host' => 'server1', 'port' => 9200],
            ['host' =>  'server2', 'port' => 9200],
    ]
]);

// Class to perform request, same as the Elastica Client
$client = $factory->buildClient();
```

Feel free to reopen this issue if you have any issue with the behavior of Elastically!

**Comment by damienalexandre** [comment]
Yeaahh.

```yaml

JoliCode\Elastically\Client:
    arguments:
        $config:
            connections:
              - { host: server1, port: 9200 }
              - { host: server2, port: 9200 }
```

This issue tracker is not for support, only for bug report by the way.

**Comment by issam-chouchane** [comment]
that rocks. I ll let you know.
