### ISSUE TITLE
Indexer::scheduleIndex(), scheduleUpdate(), scheduleCreate() - DRY principle

### ISSUE THREAD

**Issue by insekticid** [jolicode/elastically#117]
https://github.com/jolicode/elastically/blob/a116efb71eb81576bf21efab32ea6d0bbaf9b57d/src/Indexer.php#L42

These three methods Indexer::scheduleIndex(), scheduleUpdate(), scheduleCreate() have the same code , respect DRY principe and refactor this code

![image](https://user-images.githubusercontent.com/177340/194556116-78e63409-7698-4869-adde-4e07e559d20b.png)

**Comment by lyrixx** [comment]
Hello,

Thanks for your feedback.

We are fine with the current code. But If you want to contribute, feel free to open a PR.

In the meantime, I'll close this issue because it does not bring anything useful.
