### ISSUE TITLE
Compatibility with Jane is not possible without hacky code

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/elastically#12]
Elastica always reads the JSON from Elasticsearch inside an associative array (and we cannot change that without rewriting a lot of code).

So when it's time for Elastically to hydrate the DTO, we only have the array version of our "_source".

This is not an issue on the default installation of Elastically but when using Jane as the DTO + Normalizer source, it breaks.

Jane Normalizer expects `stdObject`, not arrays.

The quick and dirty hack to fix this is to run:

```
$source = json_decode(json_encode($source), false);
```

Before: https://github.com/jolicode/elastically/blob/bcb348f7ef25ac4a7dfdb627bdffb4d6127fce19/src/ResultSetBuilder.php#L65

How can we fix this in an elegant and robust way?

cc @Korbeil @joelwurtz @lyrixx 

Error:

> PHP Fatal error:  Uncaught Symfony\Component\Serializer\Exception\InvalidArgumentException: Given $data is not an object (array given). We need an object in order to continue denormalize method.

**Comment by Korbeil** [comment]
The easiest way (for me), would be to have some configuration option with Elastica to choose if we want an array (default) or an object (`\stdClass`). It would avoid using the dirty hack.

Actually they're using `json_decode` only in two places: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Response.php#L221-L223 (there is also, a third place in tests). It would be rather easy to add some configuration about that on their side.

**Comment by damienalexandre** [comment]
Just successfully tested `"jane-php/json-schema": "dev-master"` and the issue is fixed. Thanks a lot @Korbeil !
