### ISSUE TITLE
Symfony 6.2 deprecation

### ISSUE THREAD

**Issue by jmsche** [jolicode/elastically#126]
Hi,

Since I upgraded a project to Symfony 6.2 I have this deprecation:

```
Since symfony/messenger 6.2: Implementing "Symfony\Component\Messenger\Handler\MessageHandlerInterface" is deprecated, use the "Symfony\Component\Messenger\Attribute\AsMessageHandler" attribute instead. 
```

From this class: https://github.com/jolicode/elastically/blob/f918cd0465508d456cf4314a9ce0e278efc3ff2b/src/Messenger/IndexationRequestHandler.php

**Comment by lyrixx** [comment]
Hello,

I just checked and

* Symfony 4.4 is [not maintained anymore](https://symfony.com/releases)
* Attribut [exists in 5.4](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Messenger/Attribute/AsMessageHandler.php) 

So we need to:

* bump the deps to Symfony 5.4
* use the attributs

**Comment by damienalexandre** [comment]
The first item in this list is done.

Can someone provide the pull request to use the new attribute?

Thanks!

**Comment by jmsche** [comment]
I'm wondering: is the attribute even necessary if the handler is tagged?
