### ISSUE TITLE
In the Messenger Handler, improve the "NullLogger" situation

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/elastically#17]
We remove the Elastica Logger in the Message Handler for memory / perf considerations:

```php
    public function __construct(Client $client)
    {
        $this->client = $client;

        // Disable the logs for memory concerns
        $this->client->setLogger(new NullLogger());
    }
```

But that's not ideal as I removed forever, also for calls outside the Handler.

We have to find a better way, or a better logger than Elastica built in.

**Comment by lyrixx** [comment]
Some hint for the resulution:
* Use a well configured (logger channel & co) client if not defined : https://github.com/symfony/monolog-bundle/pull/331
* Maybe remove the logger in CLI https://github.com/symfony/symfony/pull/30339

**Comment by damienalexandre** [comment]
`setLogger` has been removed from Elastica directly.
