### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by D-Kalck** [jolicode/elastically#179]
Is there any plan to support Symfony 7 ?

**Comment by timsassen** [comment]
This fork is a start https://github.com/NicolasDievart/elastically. Only composer changes for now but no php8.3 optimizations though.

**Comment by damienalexandre** [comment]
Yes this fork is here as a pull request: https://github.com/jolicode/elastically/pull/180

But there is a blocker on a dependency: https://github.com/janephp/janephp/pull/768

**Comment by damienalexandre** [comment]
Tag v1.9.0 has just been published with Symfony 7 support, thanks!
