### ISSUE TITLE
Plan to use `ruflin/elastica` version 8?

### ISSUE THREAD

**Issue by jmariller** [jolicode/elastically#186]
Hi,

First of all thank you for this library :-)

I am wondering if it is planned to use version 8 of `ruflin/elastica`, and if so when more or less?

Many thanks

**Comment by damienalexandre** [comment]
We would be happy to see Pull Request about this yes. Can you work on this?

Some difficulties could arise:

- the connections pool is now based on Elasticsearch custom https://github.com/elastic/elastic-transport-php - so our Symfony HttpClient bridge must probably be changed;
- it will probably stop working with OpenSearch, see https://github.com/elastic/elasticsearch-php/issues/1347 (not tested)

I would love for our project to be compatible with both 7 and 8.

**Comment by jmariller** [comment]
Thank you @damienalexandre for your quick feedback! Sure I can invest some time to try & contribute :slightly_smiling_face:

**Comment by jmariller** [comment]
also I forgot to mention that I am not sure if we can make it work with both versions, as the namespace for different classes (e.g. `Client`) has changed between 7 and 8.

**Comment by VincentLanglet** [comment]
The 8.0.0 version is now released https://github.com/ruflin/Elastica/releases/tag/8.0.0

**Comment by jmariller** [comment]
Thanks @VincentLanglet for the update!

@damienalexandre so I started to work on it and now I get following error message for many of the PhpUnit tests:
`Elastic\Transport\Exception\NoNodeAvailableException: Exceeded maximum number of retries (1)`

I am missing anything, should I set some environment/configuration value?

**Comment by damienalexandre** [comment]
The tests are running against a real Elasticsearch.

You can run this:

```
make start
make test
make stop
```

It will boot a ES node via Docker and expose port 9999 (we don't use the default 9200 port to avoid touching any real Elasticsearch node you may have on your computer).

**Comment by jmariller** [comment]
I had actually tried to start the docker ES node as I saw the makefile, however I still get exactly the same error message :disappointed: any other idea?

**Comment by jmariller** [comment]
hi @damienalexandre so I tried once again to make this work without success, would you have any other hint?

**Comment by damienalexandre** [comment]
Could you show the console output?
Can you run `docker ps`?

**Comment by jmariller** [comment]
sure, here it is:

**console output (just an extract)**
![image](https://github.com/jolicode/elastically/assets/48550159/57a8e504-888a-4f8f-91a9-3b819d955090)


**`docker ps`**
![image](https://github.com/jolicode/elastically/assets/48550159/fcafb0a5-ac67-4a17-bfb6-37997aa551be)

**Comment by damienalexandre** [comment]
Can you open http://127.0.0.1:9999/ in a browser? 

What does `curl http://127.0.0.1:9999/` get you?

**Comment by jmariller** [comment]
This is what I get when opening this in a browser:
![image](https://github.com/jolicode/elastically/assets/48550159/195e85e7-923f-4401-af9f-3243b5bf6e48)

And with curl (essentially the same):
![image](https://github.com/jolicode/elastically/assets/48550159/89ea6a17-84c7-4351-8083-912473e00d11)

**Comment by damienalexandre** [comment]
I don't know what's happening but:

- you have a working php
- you have a working elasticsearch

Is there something we don't know? Do you have a proxy? 

Can you go to http://127.0.0.1:9999/_cluster/health?pretty and paste the result?

**Comment by jmariller** [comment]
Thanks for taking the time to help :pray:

Here is the outcome of that URL:
```json
{
"cluster_name": "docker-cluster",
"status": "green",
"timed_out": false,
"number_of_nodes": 1,
"number_of_data_nodes": 1,
"active_primary_shards": 0,
"active_shards": 0,
"relocating_shards": 0,
"initializing_shards": 0,
"unassigned_shards": 0,
"delayed_unassigned_shards": 0,
"number_of_pending_tasks": 0,
"number_of_in_flight_fetch": 0,
"task_max_waiting_in_queue_millis": 0,
"active_shards_percent_as_number": 100
}
```

**Comment by damienalexandre** [comment]
Status green, it should work!

You test from "master" or with your updated dependencies? It looks like the Elastica client is not properly configured, that may be a regression from version 8.

**Comment by jmariller** [comment]
aaah got it, it is indeed an issue from version 8! I reverted my changes and it works fine :tada: alright then, I need to investigate further :sweat_smile:  thanks again so much for your support :pray: 

ps: if anyone sees this and wants to help too, please do :slightly_smiling_face:

**Comment by jmariller** [comment]
thanks @jderusse I have actually also just noticed the same while trying to run the tests with `elasticsearch` without updating the docker image :+1: 

@damienalexandre I am making some progress, now some more tests are green :tada:

**Comment by jmariller** [comment]
short update, now I have all tests green besides the one for the `HttpClientTransport` where I might need some help - I'll do as much as I can :slightly_smiling_face:

**Comment by GaryPEGEOT** [comment]
Hi @jmariller ! Are you still working on this? Maybe I can help on the HttpClientTransport issue

**Comment by jmariller** [comment]
hi @GaryPEGEOT! no, at the moment I do not have capacity unfortunately. So if you could help it would be great - you can check out my PR and work directly on it if you want :slightly_smiling_face:  thanks!

**Comment by GaryPEGEOT** [comment]
Hi @damienalexandre!

Correct me if I'm wrong, but it looks like `JoliCode\Elastically\Transport\HttpClientTransport` will not have much sense with ruflin's Elastica v8:

1. AbstractTransport is gone
2. `Elastic\Transport\Transport` is a final class

And maybe more importantly, we don't really need it anymore, as you can specify `$config['transport_config']['http_client']` directly, and provide it with your own `Symfony\Component\HttpClient\Psr18Client`.

We could update `ElasticallyExtension` so that given a client it automatically create the PSR client.

**Comment by damienalexandre** [comment]
You are absolutely right, and what you suggest looks good, thanks :+1:

**Comment by GaryPEGEOT** [comment]
I'm creating a PR on damien's fork to remove the transport while adding test to make sure you can specify your own PSR Compliant client if you want to. This will be a BC break tho, so I guess we need to target a new branch like `next` instead of master?

**Comment by damienalexandre** [comment]
This can be shipped as a new major Elastically version. Can we make sure update the documentation as well?

**Comment by VincentLanglet** [comment]
> I'm creating a PR on damien's fork 

Wouldn't it better to do it directly on this repo ?

**Comment by damienalexandre** [comment]
I have some clean up to do before a release. For example we must remove OpenSearch from supported products :disappointed:

**Comment by damienalexandre** [comment]
Version 2.0 of Elastically, with Elastica 8, is now available! Thanks everyone!
