### ISSUE TITLE
[Bug] Support Symfony Messenger serializer

### ISSUE THREAD

**Issue by sfmok** [jolicode/elastically#197]
Hi,

I was surprised to see that elastically only supports `messenger.transport.native_php_serializer` and not `messenger.transport.symfony_serializer`. The native PHP serializer outputs messages in an unreadable format, making manual retries difficult, whereas the Symfony serializer produces JSON messages that are much easier to read and retry.

It would be beneficial for elastically to support `messenger.transport.symfony_serializer` as well.

**Comment by damienalexandre** [comment]
Agreed, would you mind sending a PR? We are about to release version 2.0 so a breaking change is acceptable.

**Comment by sfmok** [comment]
I will try to push a PR soon.

**Comment by sfmok** [comment]
It seems we have a bug here not feature. Symfony serializer normalizes the `operations` property of `MultipleIndexationRequest` to an associative array instead of an array of `IndexationRequest` objects and that's due to missing of PHPDoc annotations on `getOperations`

Ref: https://github.com/jolicode/elastically/blob/master/src/Messenger/MultipleIndexationRequest.php

**Comment by damienalexandre** [comment]
Thanks!
