### ISSUE TITLE
Use DTO with Symfony

### ISSUE THREAD

**Issue by prugala** [jolicode/elastically#202]
I'm trying to map and send DTO but I'm getting error:
`The class 'App\ElasticSearch\Model\User' was not found in the chain configured namespaces App\Entity, Gesdinet\JWTRefreshTokenBundle\Entity`

Config:
```
            index_class_mapping:
                user: App\ElasticSearch\Model\User
```

Indexing:
```
use App\ElasticSearch\Model\User as ESUser;

$this->messageBus->dispatch(new IndexationRequest(ESUser::class, $user->getId()->toString(), IndexationRequestHandler::OP_INDEX));
```

If I change on entity all works, but I want to fetch data from ES as DTO object no entity. There is possible?

**Comment by damienalexandre** [comment]
I don't think this Exception comes from Elastically, can you share the stacktrace & the code you use to "search"?

**Comment by prugala** [comment]
```
15:56:56 WARNING   [messenger] Error thrown while handling message JoliCode\Elastically\Messenger\IndexationRequest. Sending for retry #3 using 4278 ms delay. Error: "Handling "JoliCode\Elastically\Messenger\IndexationRequest" failed: The class 'App\ElasticSearch\Model\User' was not found in the chain configured namespaces App\Entity, Gesdinet\JWTRefreshTokenBundle\Entity" ["class" => "JoliCode\Elastically\Messenger\IndexationRequest","message_id" => null,"retryCount" => 3,"delay" => 4278,"error" => "Handling "JoliCode\Elastically\Messenger\IndexationRequest" failed: The class 'App\ElasticSearch\Model\User' was not found in the chain configured namespaces App\Entity, Gesdinet\JWTRefreshTokenBundle\Entity","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]

```

Problem is not with search, with indexing only.
For search Im using
```
$this->client->getIndex('user')->search()->getResults()
```

If I change in config `index_class_mapping` on Entity class and during indexing:
`new IndexationRequest(User::class, $user->getId()->toString(), IndexationRequestHandler::OP_INDEX)`
* User:class - `App\Entity\User`

Document is created in ES, next I change in config mapping on my DTO my search returns DTO as model :)

**Comment by damienalexandre** [comment]
This Exception is from Doctrine.

https://github.com/doctrine/orm/discussions/8687

Are you using Doctrine somewhere?

Can you share the code of your DocumentExchanger?

As per the documentation:

> The IndexationRequestHandler service depends on an implementation of JoliCode\Elastically\Messenger\DocumentExchangerInterface, which isn't provided by this library. You must provide a service that implements this interface, so you can plug your database or any other source of truth.

**Comment by prugala** [comment]
@damienalexandre Oh ok my bad. Yes I have in my `DocumentExchanger`
`$entity = $this->entityManager->getRepository($className)->find(Uuid::fromString($id));`

I should map my DTO class on Entity class to get repository. 

Thanks for help :)

**Comment by damienalexandre** [comment]
I'm closing the issue then, feel free to reopen if you get a new error!
