### ISSUE TITLE
Get Index/Mapping definition through annotation / database / whatever

### ISSUE THREAD

**Issue by ismail1432** [jolicode/elastically#22]
Hello :wave: 
Thanks for this library :+1: 

There is few months I had to work on a solution to define mapping and instead of using yaml I used annotations, do you think it's relevant to add a workaound this to this lib ?

```php
use App\Search\Annotation as Els;

/**
 * @Els\Index(
 *     name="product",
 *     settings={
 *         "analysis": {
 *          "number_of_replicas": 1,
 *          "refresh_interval": 60s,
 *             "analyser": {
 *                 "bpm_analyser": {
 *                     "tokenizer": "standard"
 *                 }
 *             }
 *         }
 *     })
 */
class ProductDocument

 /**
  * @var string
  *
  * @Els\ScalarMapping(type="string") // Default value
  */
 public $subtitle;

 /**
  * @var bool
  *
  * @Els\ScalarMapping(type="boolean")
  */
 public $storage = false;
```

**Comment by damienalexandre** [comment]
Hello,
Thanks for the suggestion! 

I'm not a big fan of annotation in the library directly for some reasons:

- you have to learn new syntax / naming for Elasticsearch stuff (ScalarMapping?)
- if a new option came to Elasticsearch, and is not exposed as annotation, developers are stuck / limited to what is implemented
- it can be very verbose / hard to read, if you want multiple "fiels", etc...

**But** that should be made possible. I already had questions about having another source of truth for the configuration (I have clients storing this in a database i.e.).

The **IndexBuilder** class could rely on a new abstract **Configuration** provider, which is YAML by default and can be switched by whatever your project needs. 

Would you be able to work on such change?

**Comment by ismail1432** [comment]
Thanks for the quick reply,

Even annotation seems not a good solution I think you're right and we should let developer have the choice of the source.

> The IndexBuilder class could rely on a new abstract Configuration provider[..] Would you be able to work on such change?

**Comment by damienalexandre** [comment]
The possibility to fetch the configuration freely is also needed here: https://github.com/jolicode/elastically/pull/50

The File adapter should allow this king of custom naming.

**Comment by jmsche** [comment]
As stated in #62 it would be nice to at least have PHP as an alternative language to configure analyzers & mapping.

My current case is indexing several types of Formations which have a same base "tree" but some properties differ.

I'd also like to be able to configure it using attributes if someone works on annotations as well :)

**Comment by lyrixx** [comment]
see #79

**Comment by lyrixx** [comment]
Closing since #79 has been merge. 

Thanks to everyone involved in this work 👍🏼
