### ISSUE TITLE
Add phpdocumentor/reflection-docblock as a require

### ISSUE THREAD

**Issue by lamasfoker** [jolicode/elastically#36]
At [this line](https://github.com/jolicode/elastically/blob/master/src/Client.php#L108) you instantiate `\Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor`, but as the [composer.json](https://github.com/symfony/property-info/blob/master/composer.json#L45) of symfony/property-info said if you use this class you have to make phpdocumentor/reflection-docblock as a require.

**Comment by damienalexandre** [comment]
Thanks @lamasfoker for this report,
as I said on https://github.com/monsieurbiz/SyliusSearchPlugin/issues/34#issuecomment-667210250 ; I think this static Serializer is a mistake and it should be a required option of the Client instead.

I will add the requirement right now, and work on that other matter later.

**Comment by damienalexandre** [comment]
Released in v1.0.2, thanks!
