### ISSUE TITLE
Add Client::CONFIG_INDEX_PREFIX

### ISSUE THREAD

**Issue by renanbr** [jolicode/elastically#4]
So it would make a `Client` and its `Indexer` manage only namespaced indexes. It may be useful in cases we share the same database across multiple applications.

**Comment by lyrixx** [comment]
:+1: (and also for test env)

**Comment by damienalexandre** [comment]
That's not a bad idea :+1: thank you! Will look into it.

**Comment by damienalexandre** [comment]
Aaanndd it's done: https://github.com/jolicode/elastically#clientconfig_index_prefix-optional

Thanks a lot!
