### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/elastically#43]
Now that version 1 is out and the package is more used, I think it's time for a real changelog.

GitHub Releases create a non-portable changelog that can only be displayed to users within the context of GitHub. I don't like that.

We need a real CHANGELOG.md file at the root of the project, following the format of https://keepachangelog.com/en/1.0.0/

All previous releases should also be added.

**Comment by ChandlerKlein** [comment]
Hi there, could you assign this issue to me? Thanks!

**Comment by ChandlerKlein** [comment]
Please add 'hacktoberfest-accepted ' label to the pull request if it looks good, thanks!
