### ISSUE TITLE
Search in multiple indices

### ISSUE THREAD

**Issue by JochenRousse** [jolicode/elastically#51]
Hi,

I was looking for a way to run a search query in more than one index at the same time.
From what I've seen, this does not seem possible at the moment with Elastically, do you have any plans on implementing this feature in the framework ?

**Comment by damienalexandre** [comment]
Actually you can already but the API is not obvious.

```php
        $search = $client->getIndex('post')->createSearch();
        $search->addIndex('comment');
        $search->addIndex('foobar');
        $search->setQuery($searchQuery);
```

The ResultSetBuilder will hydrate the correct DTO for each index found in the results.

Can you have a try?

**Comment by JochenRousse** [comment]
Thank you for the quick reply, I'll give it a try !

**Comment by JochenRousse** [comment]
Update: it worked like a charm. 
Thank you very much @damienalexandre!
