### ISSUE TITLE
Allow PHP configuration instead of YAML

### ISSUE THREAD

**Issue by jmsche** [jolicode/elastically#62]
It would be nice to be able to configure analyzers & mapping using PHP instead of YAML. If I read the IndexBuilder correctly, only YAML is allowed right now.

**Comment by damienalexandre** [comment]
Hi :wave: 

Going full YAML was in fact too restrictive, you are right. 

We already have an issue for this here: https://github.com/jolicode/elastically/issues/22 so I'm closing this one as duplicate.

Thanks a lot for this feedback as it helps driving priorities for the next version.

**Comment by jmsche** [comment]
My bad, didn't search enough :)
